// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkTjJlNUesxBdO6WcOOy-5fha-HyJb1ng',
    appId: '1:415759426864:web:93e452ce7bae61e21b54f5',
    messagingSenderId: '415759426864',
    projectId: 'alfabetizando-8e771',
    authDomain: 'alfabetizando-8e771.firebaseapp.com',
    databaseURL: 'https://alfabetizando-8e771-default-rtdb.firebaseio.com',
    storageBucket: 'alfabetizando-8e771.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDloCGxiOE8j8RbVGx82GuhAwqBu3_zpns',
    appId: '1:415759426864:android:b8ecadbb30219c301b54f5',
    messagingSenderId: '415759426864',
    projectId: 'alfabetizando-8e771',
    databaseURL: 'https://alfabetizando-8e771-default-rtdb.firebaseio.com',
    storageBucket: 'alfabetizando-8e771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3nQDh9lpv8gdOtyepb9YSVerx1TvHKEE',
    appId: '1:415759426864:ios:5537dfe0fda2324f1b54f5',
    messagingSenderId: '415759426864',
    projectId: 'alfabetizando-8e771',
    databaseURL: 'https://alfabetizando-8e771-default-rtdb.firebaseio.com',
    storageBucket: 'alfabetizando-8e771.appspot.com',
    iosClientId: '415759426864-f7du59lfi0vgpu6j6v3r8mgq0rod7bq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.alfabetizando',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3nQDh9lpv8gdOtyepb9YSVerx1TvHKEE',
    appId: '1:415759426864:ios:5537dfe0fda2324f1b54f5',
    messagingSenderId: '415759426864',
    projectId: 'alfabetizando-8e771',
    databaseURL: 'https://alfabetizando-8e771-default-rtdb.firebaseio.com',
    storageBucket: 'alfabetizando-8e771.appspot.com',
    iosClientId: '415759426864-f7du59lfi0vgpu6j6v3r8mgq0rod7bq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.alfabetizando',
  );
}
